// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to explain the reasoning behind drink recommendations.
 *
 * - explainRecommendation - A function that handles explaining the recommendation.
 * - ExplainRecommendationInput - The input type for the explainRecommendation function.
 * - ExplainRecommendationOutput - The return type for the explainRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainRecommendationInputSchema = z.object({
  drink: z.string().describe('The name of the recommended drink.'),
  reason: z.string().describe('The original reason for the recommendation.'),
  weatherCondition: z.string().optional().describe('The current weather condition.'),
  timeOfDay: z.string().optional().describe('The current time of day.'),
  userTaste: z.string().optional().describe('The user\s taste preferences.'),
});
export type ExplainRecommendationInput = z.infer<typeof ExplainRecommendationInputSchema>;

const ExplainRecommendationOutputSchema = z.object({
  explanation: z.string().describe('A detailed explanation of why the drink was recommended.'),
});
export type ExplainRecommendationOutput = z.infer<typeof ExplainRecommendationOutputSchema>;

export async function explainRecommendation(input: ExplainRecommendationInput): Promise<ExplainRecommendationOutput> {
  return explainRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'explainRecommendationPrompt',
  input: {schema: ExplainRecommendationInputSchema},
  output: {schema: ExplainRecommendationOutputSchema},
  prompt: `You are an expert beverage consultant at Starbucks.

You are provided with the following information:

Drink: {{{drink}}}
Original Reason: {{{reason}}}
Weather Condition: {{{weatherCondition}}}
Time of Day: {{{timeOfDay}}}
User Taste: {{{userTaste}}}

Explain in detail, but concisely, why this drink is recommended based on the provided information. Focus on how each factor contributes to the suitability of the drink.
`,
});

const explainRecommendationFlow = ai.defineFlow(
  {
    name: 'explainRecommendationFlow',
    inputSchema: ExplainRecommendationInputSchema,
    outputSchema: ExplainRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
